import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  console.log('🔮 Seeding Mystic Tarot database...')

  // Create default deck
  const deck = await prisma.deck.upsert({
    where: { slug: 'rider-waite' },
    update: {},
    create: {
      name: 'Rider-Waite',
      slug: 'rider-waite',
      description: 'The classic Rider-Waite tarot deck, public domain',
      isDefault: true,
    },
  })

  console.log('✅ Deck created:', deck.name)

  const cards = [
    // ═══════════════════════════════
    // MAJOR ARCANA (22 cards)
    // ═══════════════════════════════
    {
      nameEn: 'The Fool',
      nameRu: 'Шут',
      arcana: 'MAJOR' as const,
      suit: null,
      number: 0,
      keywords: ['new beginnings', 'innocence', 'adventure', 'spontaneity'],
      meaningUpright: { keywords: ['new beginnings', 'innocence', 'free spirit'], description: 'A new journey begins. Embrace the unknown with an open heart.' },
      meaningReversed: { keywords: ['recklessness', 'naivety', 'foolishness'], description: 'Reckless behavior or naivety may be causing problems.' },
      description: 'The Fool represents the beginning of a journey, unlimited potential, and the courage to leap into the unknown.',
      imageUrl: '/cards/rider-waite/major/00-fool.jpg',
    },
    {
      nameEn: 'The Magician',
      nameRu: 'Маг',
      arcana: 'MAJOR' as const,
      suit: null,
      number: 1,
      keywords: ['willpower', 'manifestation', 'skill', 'resourcefulness'],
      meaningUpright: { keywords: ['manifestation', 'willpower', 'skill'], description: 'You have all the tools you need. Use your will to manifest your desires.' },
      meaningReversed: { keywords: ['manipulation', 'poor planning', 'untapped potential'], description: 'Skills are being misused or potential remains unrealized.' },
      description: 'The Magician represents the power of will, skill, and the ability to manifest desires into reality.',
      imageUrl: '/cards/rider-waite/major/01-magician.jpg',
    },
    {
      nameEn: 'The High Priestess',
      nameRu: 'Верховная Жрица',
      arcana: 'MAJOR' as const,
      suit: null,
      number: 2,
      keywords: ['intuition', 'mystery', 'inner knowledge', 'subconscious'],
      meaningUpright: { keywords: ['intuition', 'sacred knowledge', 'mystery'], description: 'Trust your intuition. The answers lie within.' },
      meaningReversed: { keywords: ['secrets', 'disconnection', 'hidden agendas'], description: 'You may be ignoring your inner voice or hiding the truth.' },
      description: 'The High Priestess embodies intuition, mystery, and the deep wisdom of the subconscious mind.',
      imageUrl: '/cards/rider-waite/major/02-high-priestess.jpg',
    },
    {
      nameEn: 'The Empress',
      nameRu: 'Императрица',
      arcana: 'MAJOR' as const,
      suit: null,
      number: 3,
      keywords: ['fertility', 'abundance', 'nurturing', 'nature'],
      meaningUpright: { keywords: ['femininity', 'beauty', 'nature', 'abundance'], description: 'A time of growth, creativity, and abundance. Nurture your projects.' },
      meaningReversed: { keywords: ['dependence', 'smothering', 'emptiness'], description: 'Creative block or neglect of self-care may be present.' },
      description: 'The Empress represents fertility, abundance, and the nurturing power of nature and creativity.',
      imageUrl: '/cards/rider-waite/major/03-empress.jpg',
    },
    {
      nameEn: 'The Emperor',
      nameRu: 'Император',
      arcana: 'MAJOR' as const,
      suit: null,
      number: 4,
      keywords: ['authority', 'structure', 'control', 'fatherhood'],
      meaningUpright: { keywords: ['authority', 'structure', 'stability'], description: 'Establish order and take charge. Leadership and discipline are needed.' },
      meaningReversed: { keywords: ['tyranny', 'rigidity', 'domination'], description: 'Excessive control or abuse of authority is causing harm.' },
      description: 'The Emperor symbolizes authority, structure, and the power of rational thought and discipline.',
      imageUrl: '/cards/rider-waite/major/04-emperor.jpg',
    },
    {
      nameEn: 'The Hierophant',
      nameRu: 'Иерофант',
      arcana: 'MAJOR' as const,
      suit: null,
      number: 5,
      keywords: ['tradition', 'conformity', 'morality', 'spiritual wisdom'],
      meaningUpright: { keywords: ['spiritual wisdom', 'tradition', 'institutions'], description: 'Seek guidance from established traditions or a mentor.' },
      meaningReversed: { keywords: ['rebellion', 'subversiveness', 'new approaches'], description: 'Challenging conventions or breaking free from dogma.' },
      description: 'The Hierophant represents spiritual authority, tradition, and the transmission of sacred knowledge.',
      imageUrl: '/cards/rider-waite/major/05-hierophant.jpg',
    },
    {
      nameEn: 'The Lovers',
      nameRu: 'Влюблённые',
      arcana: 'MAJOR' as const,
      suit: null,
      number: 6,
      keywords: ['love', 'harmony', 'relationships', 'choices'],
      meaningUpright: { keywords: ['love', 'union', 'alignment', 'choices'], description: 'A significant relationship or important choice aligned with your values.' },
      meaningReversed: { keywords: ['disharmony', 'imbalance', 'misalignment'], description: 'Conflict in relationships or choices made against your values.' },
      description: 'The Lovers represent love, harmony, and the profound choices that define our path.',
      imageUrl: '/cards/rider-waite/major/06-lovers.jpg',
    },
    {
      nameEn: 'The Chariot',
      nameRu: 'Колесница',
      arcana: 'MAJOR' as const,
      suit: null,
      number: 7,
      keywords: ['control', 'willpower', 'victory', 'determination'],
      meaningUpright: { keywords: ['control', 'willpower', 'success', 'action'], description: 'Victory through determination and control. Move forward with confidence.' },
      meaningReversed: { keywords: ['lack of control', 'aggression', 'obstacles'], description: 'Loss of direction or lack of willpower is blocking progress.' },
      description: 'The Chariot symbolizes triumph, determination, and the mastery of opposing forces.',
      imageUrl: '/cards/rider-waite/major/07-chariot.jpg',
    },
    {
      nameEn: 'Strength',
      nameRu: 'Сила',
      arcana: 'MAJOR' as const,
      suit: null,
      number: 8,
      keywords: ['strength', 'courage', 'patience', 'compassion'],
      meaningUpright: { keywords: ['strength', 'courage', 'inner power'], description: 'Inner strength and courage will overcome challenges with grace.' },
      meaningReversed: { keywords: ['weakness', 'self-doubt', 'cowardice'], description: 'Lack of confidence or giving in to fear and weakness.' },
      description: 'Strength represents inner courage, patience, and the power of compassion over brute force.',
      imageUrl: '/cards/rider-waite/major/08-strength.jpg',
    },
    {
      nameEn: 'The Hermit',
      nameRu: 'Отшельник',
      arcana: 'MAJOR' as const,
      suit: null,
      number: 9,
      keywords: ['soul searching', 'introspection', 'solitude', 'guidance'],
      meaningUpright: { keywords: ['introspection', 'solitude', 'inner guidance'], description: 'A period of reflection and soul-searching is needed.' },
      meaningReversed: { keywords: ['isolation', 'loneliness', 'withdrawal'], description: 'Excessive isolation or refusal to seek help from others.' },
      description: 'The Hermit embodies the search for inner truth through solitude and quiet contemplation.',
      imageUrl: '/cards/rider-waite/major/09-hermit.jpg',
    },
    {
      nameEn: 'Wheel of Fortune',
      nameRu: 'Колесо Фортуны',
      arcana: 'MAJOR' as const,
      suit: null,
      number: 10,
      keywords: ['good luck', 'karma', 'life cycles', 'fate'],
      meaningUpright: { keywords: ['luck', 'fate', 'turning point', 'cycles'], description: 'A turning point is at hand. The wheel of fortune spins in your favor.' },
      meaningReversed: { keywords: ['bad luck', 'resistance', 'breaking cycles'], description: 'Resisting change or experiencing a run of bad luck.' },
      description: 'The Wheel of Fortune represents the cycles of life, fate, and the ever-turning nature of destiny.',
      imageUrl: '/cards/rider-waite/major/10-wheel-of-fortune.jpg',
    },
    {
      nameEn: 'Justice',
      nameRu: 'Справедливость',
      arcana: 'MAJOR' as const,
      suit: null,
      number: 11,
      keywords: ['justice', 'fairness', 'truth', 'cause and effect'],
      meaningUpright: { keywords: ['justice', 'fairness', 'truth', 'law'], description: 'Justice will be served. Act with integrity and fairness.' },
      meaningReversed: { keywords: ['unfairness', 'dishonesty', 'lack of accountability'], description: 'Injustice or dishonesty in a situation requires attention.' },
      description: 'Justice embodies fairness, truth, and the law of cause and effect in all matters.',
      imageUrl: '/cards/rider-waite/major/11-justice.jpg',
    },
    {
      nameEn: 'The Hanged Man',
      nameRu: 'Повешенный',
      arcana: 'MAJOR' as const,
      suit: null,
      number: 12,
      keywords: ['suspension', 'sacrifice', 'new perspective', 'surrender'],
      meaningUpright: { keywords: ['pause', 'surrender', 'letting go', 'new perspective'], description: 'A voluntary pause brings new insight. Surrender to gain wisdom.' },
      meaningReversed: { keywords: ['stalling', 'indecision', 'resistance'], description: 'Unnecessary delays or unwillingness to make a needed sacrifice.' },
      description: 'The Hanged Man represents surrender, sacrifice, and seeing the world from a new perspective.',
      imageUrl: '/cards/rider-waite/major/12-hanged-man.jpg',
    },
    {
      nameEn: 'Death',
      nameRu: 'Смерть',
      arcana: 'MAJOR' as const,
      suit: null,
      number: 13,
      keywords: ['endings', 'change', 'transformation', 'transition'],
      meaningUpright: { keywords: ['endings', 'transformation', 'transition'], description: 'An ending makes way for a new beginning. Embrace transformation.' },
      meaningReversed: { keywords: ['resistance to change', 'stagnation', 'fear'], description: 'Resisting necessary change is causing stagnation.' },
      description: 'Death represents transformation, endings, and the inevitable cycle of change and renewal.',
      imageUrl: '/cards/rider-waite/major/13-death.jpg',
    },
    {
      nameEn: 'Temperance',
      nameRu: 'Умеренность',
      arcana: 'MAJOR' as const,
      suit: null,
      number: 14,
      keywords: ['balance', 'moderation', 'patience', 'purpose'],
      meaningUpright: { keywords: ['balance', 'moderation', 'patience', 'purpose'], description: 'Find balance and harmony. Patience and moderation lead to success.' },
      meaningReversed: { keywords: ['imbalance', 'excess', 'lack of patience'], description: 'Excess or imbalance in some area of life needs correction.' },
      description: 'Temperance embodies balance, moderation, and the art of blending opposites into harmony.',
      imageUrl: '/cards/rider-waite/major/14-temperance.jpg',
    },
    {
      nameEn: 'The Devil',
      nameRu: 'Дьявол',
      arcana: 'MAJOR' as const,
      suit: null,
      number: 15,
      keywords: ['shadow self', 'attachment', 'bondage', 'materialism'],
      meaningUpright: { keywords: ['bondage', 'materialism', 'shadow self'], description: 'You may be bound by unhealthy attachments or limiting beliefs.' },
      meaningReversed: { keywords: ['releasing limiting beliefs', 'freedom', 'reclaiming power'], description: 'Breaking free from addiction, bondage, or limiting patterns.' },
      description: 'The Devil represents our shadow self, material attachments, and the chains we place upon ourselves.',
      imageUrl: '/cards/rider-waite/major/15-devil.jpg',
    },
    {
      nameEn: 'The Tower',
      nameRu: 'Башня',
      arcana: 'MAJOR' as const,
      suit: null,
      number: 16,
      keywords: ['sudden change', 'upheaval', 'chaos', 'revelation'],
      meaningUpright: { keywords: ['sudden change', 'upheaval', 'revelation'], description: 'A sudden, dramatic change destroys old structures to make way for truth.' },
      meaningReversed: { keywords: ['avoidance', 'fear of change', 'delayed disaster'], description: 'Avoiding an inevitable upheaval only delays and worsens it.' },
      description: 'The Tower represents sudden upheaval, destruction of false foundations, and necessary chaos.',
      imageUrl: '/cards/rider-waite/major/16-tower.jpg',
    },
    {
      nameEn: 'The Star',
      nameRu: 'Звезда',
      arcana: 'MAJOR' as const,
      suit: null,
      number: 17,
      keywords: ['hope', 'faith', 'renewal', 'inspiration'],
      meaningUpright: { keywords: ['hope', 'inspiration', 'serenity', 'renewal'], description: 'A beacon of hope and renewal. Have faith in the future.' },
      meaningReversed: { keywords: ['despair', 'hopelessness', 'disconnection'], description: 'Loss of faith or hope. Reconnect with your inner light.' },
      description: 'The Star represents hope, inspiration, and the renewal of faith after a time of darkness.',
      imageUrl: '/cards/rider-waite/major/17-star.jpg',
    },
    {
      nameEn: 'The Moon',
      nameRu: 'Луна',
      arcana: 'MAJOR' as const,
      suit: null,
      number: 18,
      keywords: ['illusion', 'fear', 'the unconscious', 'confusion'],
      meaningUpright: { keywords: ['illusion', 'fear', 'the unconscious'], description: 'Things are not as they appear. Navigate uncertainty with caution.' },
      meaningReversed: { keywords: ['release of fear', 'repressed emotions', 'confusion'], description: 'Fears and illusions are being released. Clarity is emerging.' },
      description: 'The Moon represents the realm of illusion, dreams, and the mysterious depths of the unconscious.',
      imageUrl: '/cards/rider-waite/major/18-moon.jpg',
    },
    {
      nameEn: 'The Sun',
      nameRu: 'Солнце',
      arcana: 'MAJOR' as const,
      suit: null,
      number: 19,
      keywords: ['positivity', 'fun', 'warmth', 'success'],
      meaningUpright: { keywords: ['success', 'radiance', 'abundance', 'joy'], description: 'Joy, success, and vitality illuminate your path. A time of triumph.' },
      meaningReversed: { keywords: ['inner child', 'feeling down', 'overly optimistic'], description: 'Temporary setbacks or excessive optimism clouding judgment.' },
      description: 'The Sun radiates positivity, success, and the pure joy of being alive and thriving.',
      imageUrl: '/cards/rider-waite/major/19-sun.jpg',
    },
    {
      nameEn: 'Judgement',
      nameRu: 'Суд',
      arcana: 'MAJOR' as const,
      suit: null,
      number: 20,
      keywords: ['judgement', 'rebirth', 'inner calling', 'absolution'],
      meaningUpright: { keywords: ['reflection', 'reckoning', 'awakening'], description: 'A moment of profound awakening and calling. Heed the higher call.' },
      meaningReversed: { keywords: ['self-doubt', 'ignoring the call', 'lack of self-awareness'], description: 'Ignoring an important calling or refusing self-reflection.' },
      description: 'Judgement represents a spiritual awakening, a calling to rise up, and the review of past actions.',
      imageUrl: '/cards/rider-waite/major/20-judgement.jpg',
    },
    {
      nameEn: 'The World',
      nameRu: 'Мир',
      arcana: 'MAJOR' as const,
      suit: null,
      number: 21,
      keywords: ['completion', 'integration', 'accomplishment', 'wholeness'],
      meaningUpright: { keywords: ['completion', 'achievement', 'wholeness'], description: 'A cycle is complete. Celebrate your achievement and integrate the lessons.' },
      meaningReversed: { keywords: ['seeking personal closure', 'short-cuts', 'delays'], description: 'A cycle remains incomplete. What needs to be finished?' },
      description: 'The World represents completion, wholeness, and the successful integration of all life experiences.',
      imageUrl: '/cards/rider-waite/major/21-world.jpg',
    },

    // ═══════════════════════════════
    // MINOR ARCANA — WANDS (14 cards)
    // ═══════════════════════════════
    {
      nameEn: 'Ace of Wands',
      nameRu: 'Туз Жезлов',
      arcana: 'MINOR' as const,
      suit: 'WANDS' as const,
      number: 1,
      keywords: ['inspiration', 'new opportunities', 'growth', 'potential'],
      meaningUpright: { keywords: ['inspiration', 'power', 'creation'], description: 'A spark of inspiration ignites a new creative venture.' },
      meaningReversed: { keywords: ['delays', 'lack of motivation', 'creative blocks'], description: 'Creative energy is blocked or a new venture is delayed.' },
      description: 'The Ace of Wands represents the pure creative spark and the potential of new beginnings.',
      imageUrl: '/cards/rider-waite/wands/ace-wands.jpg',
    },
    {
      nameEn: 'Two of Wands',
      nameRu: 'Двойка Жезлов',
      arcana: 'MINOR' as const,
      suit: 'WANDS' as const,
      number: 2,
      keywords: ['future planning', 'progress', 'decisions', 'discovery'],
      meaningUpright: { keywords: ['planning', 'future', 'progress'], description: 'You stand at a crossroads, planning your next bold move.' },
      meaningReversed: { keywords: ['fear of unknown', 'lack of planning', 'playing it safe'], description: 'Fear is preventing you from taking the next step forward.' },
      description: 'The Two of Wands represents future planning and the courage to pursue your vision.',
      imageUrl: '/cards/rider-waite/wands/02-wands.jpg',
    },
    {
      nameEn: 'Three of Wands',
      nameRu: 'Тройка Жезлов',
      arcana: 'MINOR' as const,
      suit: 'WANDS' as const,
      number: 3,
      keywords: ['expansion', 'foresight', 'overseas', 'leadership'],
      meaningUpright: { keywords: ['expansion', 'foresight', 'overseas opportunities'], description: 'Your plans are expanding beyond initial horizons. Look further ahead.' },
      meaningReversed: { keywords: ['playing small', 'lack of foresight', 'obstacles'], description: 'Obstacles are preventing expansion or vision is too limited.' },
      description: 'The Three of Wands signifies expansion, foresight, and the fruits of early efforts.',
      imageUrl: '/cards/rider-waite/wands/03-wands.jpg',
    },
    {
      nameEn: 'Four of Wands',
      nameRu: 'Четвёрка Жезлов',
      arcana: 'MINOR' as const,
      suit: 'WANDS' as const,
      number: 4,
      keywords: ['celebration', 'joy', 'harmony', 'homecoming'],
      meaningUpright: { keywords: ['celebration', 'harmony', 'community'], description: 'A time of celebration, joy, and coming home.' },
      meaningReversed: { keywords: ['conflict', 'transition', 'lack of support'], description: 'Disruption of harmony or a difficult homecoming.' },
      description: 'The Four of Wands represents celebration, stability, and the joy of community.',
      imageUrl: '/cards/rider-waite/wands/04-wands.jpg',
    },
    {
      nameEn: 'Five of Wands',
      nameRu: 'Пятёрка Жезлов',
      arcana: 'MINOR' as const,
      suit: 'WANDS' as const,
      number: 5,
      keywords: ['conflict', 'competition', 'tension', 'diversity'],
      meaningUpright: { keywords: ['competition', 'conflict', 'tension'], description: 'Conflict and competition test your resolve. Stand your ground.' },
      meaningReversed: { keywords: ['avoidance', 'conflict resolution', 'release'], description: 'Avoiding conflict or finding peaceful resolution.' },
      description: 'The Five of Wands represents conflict, competition, and the challenge of differing perspectives.',
      imageUrl: '/cards/rider-waite/wands/05-wands.jpg',
    },
    {
      nameEn: 'Six of Wands',
      nameRu: 'Шестёрка Жезлов',
      arcana: 'MINOR' as const,
      suit: 'WANDS' as const,
      number: 6,
      keywords: ['success', 'public recognition', 'progress', 'self-confidence'],
      meaningUpright: { keywords: ['victory', 'success', 'public recognition'], description: 'Victory and public recognition reward your efforts.' },
      meaningReversed: { keywords: ['ego', 'failure', 'lack of recognition'], description: 'Success is delayed or recognition is withheld.' },
      description: 'The Six of Wands represents victory, public recognition, and well-deserved success.',
      imageUrl: '/cards/rider-waite/wands/06-wands.jpg',
    },
    {
      nameEn: 'Seven of Wands',
      nameRu: 'Семёрка Жезлов',
      arcana: 'MINOR' as const,
      suit: 'WANDS' as const,
      number: 7,
      keywords: ['challenge', 'competition', 'perseverance', 'defensiveness'],
      meaningUpright: { keywords: ['challenge', 'perseverance', 'defensive'], description: 'Hold your ground against challenges. Perseverance will prevail.' },
      meaningReversed: { keywords: ['giving up', 'overwhelmed', 'yielding'], description: 'Feeling overwhelmed by opposition or giving up too easily.' },
      description: 'The Seven of Wands represents perseverance, courage, and defending your position.',
      imageUrl: '/cards/rider-waite/wands/07-wands.jpg',
    },
    {
      nameEn: 'Eight of Wands',
      nameRu: 'Восьмёрка Жезлов',
      arcana: 'MINOR' as const,
      suit: 'WANDS' as const,
      number: 8,
      keywords: ['speed', 'action', 'air travel', 'movement'],
      meaningUpright: { keywords: ['speed', 'action', 'swift change'], description: 'Events are moving quickly. Embrace the rapid pace of change.' },
      meaningReversed: { keywords: ['delays', 'frustration', 'lost momentum'], description: 'Delays are frustrating progress or plans are misaligned.' },
      description: 'The Eight of Wands represents swift movement, rapid change, and the momentum of events.',
      imageUrl: '/cards/rider-waite/wands/08-wands.jpg',
    },
    {
      nameEn: 'Nine of Wands',
      nameRu: 'Девятка Жезлов',
      arcana: 'MINOR' as const,
      suit: 'WANDS' as const,
      number: 9,
      keywords: ['resilience', 'courage', 'persistence', 'last stand'],
      meaningUpright: { keywords: ['resilience', 'persistence', 'last stand'], description: 'Though weary, you have the strength to persevere to the end.' },
      meaningReversed: { keywords: ['exhaustion', 'giving up', 'stubbornness'], description: 'Exhaustion or paranoia is causing unnecessary struggle.' },
      description: 'The Nine of Wands represents resilience, persistence, and the strength to endure.',
      imageUrl: '/cards/rider-waite/wands/09-wands.jpg',
    },
    {
      nameEn: 'Ten of Wands',
      nameRu: 'Десятка Жезлов',
      arcana: 'MINOR' as const,
      suit: 'WANDS' as const,
      number: 10,
      keywords: ['burden', 'extra responsibility', 'hard work', 'completion'],
      meaningUpright: { keywords: ['burden', 'responsibility', 'hard work'], description: 'You carry a heavy burden. Delegate or release what is not yours to carry.' },
      meaningReversed: { keywords: ['doing it all', 'delegation', 'releasing burden'], description: 'Learning to let go of responsibilities and delegate effectively.' },
      description: 'The Ten of Wands represents the burden of responsibility and the weight of overextension.',
      imageUrl: '/cards/rider-waite/wands/10-wands.jpg',
    },
    {
      nameEn: 'Page of Wands',
      nameRu: 'Паж Жезлов',
      arcana: 'MINOR' as const,
      suit: 'WANDS' as const,
      number: 11,
      keywords: ['inspiration', 'ideas', 'discovery', 'limitless potential'],
      meaningUpright: { keywords: ['enthusiasm', 'exploration', 'discovery'], description: 'Embrace new ideas with enthusiasm and childlike wonder.' },
      meaningReversed: { keywords: ['lack of direction', 'procrastination', 'creating conflict'], description: 'Ideas without direction or enthusiasm without follow-through.' },
      description: 'The Page of Wands represents the enthusiastic explorer, full of new ideas and creative energy.',
      imageUrl: '/cards/rider-waite/wands/page-wands.jpg',
    },
    {
      nameEn: 'Knight of Wands',
      nameRu: 'Рыцарь Жезлов',
      arcana: 'MINOR' as const,
      suit: 'WANDS' as const,
      number: 12,
      keywords: ['energy', 'passion', 'inspired action', 'adventure'],
      meaningUpright: { keywords: ['energy', 'passion', 'adventure'], description: 'Act boldly and with passion. Energy and confidence lead the way.' },
      meaningReversed: { keywords: ['anger', 'impulsiveness', 'recklessness'], description: 'Impulsive actions or misdirected energy creates problems.' },
      description: 'The Knight of Wands represents passionate action, bold adventure, and fiery energy.',
      imageUrl: '/cards/rider-waite/wands/knight-wands.jpg',
    },
    {
      nameEn: 'Queen of Wands',
      nameRu: 'Королева Жезлов',
      arcana: 'MINOR' as const,
      suit: 'WANDS' as const,
      number: 13,
      keywords: ['courage', 'confidence', 'independence', 'social butterfly'],
      meaningUpright: { keywords: ['courage', 'confidence', 'independence'], description: 'Lead with confidence and passion. Your charisma inspires others.' },
      meaningReversed: { keywords: ['selfishness', 'jealousy', 'insecurities'], description: 'Insecurity or jealousy is undermining your natural confidence.' },
      description: 'The Queen of Wands embodies courageous, confident, and passionate feminine energy.',
      imageUrl: '/cards/rider-waite/wands/queen-wands.jpg',
    },
    {
      nameEn: 'King of Wands',
      nameRu: 'Король Жезлов',
      arcana: 'MINOR' as const,
      suit: 'WANDS' as const,
      number: 14,
      keywords: ['natural-born leader', 'vision', 'entrepreneur', 'honour'],
      meaningUpright: { keywords: ['vision', 'leadership', 'entrepreneur'], description: 'Lead with vision and inspire others with your bold example.' },
      meaningReversed: { keywords: ['impulsiveness', 'haste', 'ruthless'], description: 'Arrogance or reckless leadership is causing harm.' },
      description: 'The King of Wands represents visionary leadership, entrepreneurial spirit, and bold mastery.',
      imageUrl: '/cards/rider-waite/wands/king-wands.jpg',
    },

    // ═══════════════════════════════
    // MINOR ARCANA — CUPS (14 cards)
    // ═══════════════════════════════
    {
      nameEn: 'Ace of Cups',
      nameRu: 'Туз Кубков',
      arcana: 'MINOR' as const,
      suit: 'CUPS' as const,
      number: 1,
      keywords: ['love', 'new relationships', 'compassion', 'creativity'],
      meaningUpright: { keywords: ['love', 'new feelings', 'emotional awakening'], description: 'A new emotional beginning. Love and compassion flow freely.' },
      meaningReversed: { keywords: ['blocked emotions', 'emptiness', 'sadness'], description: 'Emotional blockages prevent the flow of love and creativity.' },
      description: 'The Ace of Cups represents the purest form of love, emotional new beginnings, and compassion.',
      imageUrl: '/cards/rider-waite/cups/ace-cups.jpg',
    },
    {
      nameEn: 'Two of Cups',
      nameRu: 'Двойка Кубков',
      arcana: 'MINOR' as const,
      suit: 'CUPS' as const,
      number: 2,
      keywords: ['unity', 'partnership', 'mutual attraction', 'connection'],
      meaningUpright: { keywords: ['unity', 'partnership', 'connection'], description: 'A beautiful partnership or connection is forming or deepening.' },
      meaningReversed: { keywords: ['imbalance', 'broken relationships', 'disconnection'], description: 'Imbalance or disconnection in an important relationship.' },
      description: 'The Two of Cups represents the joy of partnership, mutual attraction, and emotional connection.',
      imageUrl: '/cards/rider-waite/cups/02-cups.jpg',
    },
    {
      nameEn: 'Three of Cups',
      nameRu: 'Тройка Кубков',
      arcana: 'MINOR' as const,
      suit: 'CUPS' as const,
      number: 3,
      keywords: ['celebration', 'friendship', 'creativity', 'collaborations'],
      meaningUpright: { keywords: ['celebration', 'friendship', 'community'], description: 'Celebrate with loved ones. Joy and community surround you.' },
      meaningReversed: { keywords: ['overindulgence', 'gossip', 'isolation'], description: 'Overindulgence or social conflicts are disrupting harmony.' },
      description: 'The Three of Cups represents joyful celebration, friendship, and the spirit of community.',
      imageUrl: '/cards/rider-waite/cups/03-cups.jpg',
    },
    {
      nameEn: 'Four of Cups',
      nameRu: 'Четвёрка Кубков',
      arcana: 'MINOR' as const,
      suit: 'CUPS' as const,
      number: 4,
      keywords: ['meditation', 'contemplation', 'apathy', 'reevaluation'],
      meaningUpright: { keywords: ['contemplation', 'apathy', 'reevaluation'], description: 'A period of withdrawal and contemplation. Look inward for answers.' },
      meaningReversed: { keywords: ['sudden awareness', 'choosing happiness', 'acceptance'], description: 'Emerging from apathy to embrace new opportunities.' },
      description: 'The Four of Cups represents meditation, contemplation, and reassessment of emotional priorities.',
      imageUrl: '/cards/rider-waite/cups/04-cups.jpg',
    },
    {
      nameEn: 'Five of Cups',
      nameRu: 'Пятёрка Кубков',
      arcana: 'MINOR' as const,
      suit: 'CUPS' as const,
      number: 5,
      keywords: ['regret', 'failure', 'disappointment', 'pessimism'],
      meaningUpright: { keywords: ['regret', 'loss', 'disappointment'], description: 'Grief and loss are present, but not all is gone. Look to what remains.' },
      meaningReversed: { keywords: ['acceptance', 'moving on', 'finding peace'], description: 'Moving through grief toward acceptance and healing.' },
      description: 'The Five of Cups represents loss, regret, and the challenge of focusing on what remains.',
      imageUrl: '/cards/rider-waite/cups/05-cups.jpg',
    },
    {
      nameEn: 'Six of Cups',
      nameRu: 'Шестёрка Кубков',
      arcana: 'MINOR' as const,
      suit: 'CUPS' as const,
      number: 6,
      keywords: ['revisiting the past', 'childhood memories', 'innocence', 'nostalgia'],
      meaningUpright: { keywords: ['nostalgia', 'childhood', 'innocence'], description: 'Reconnecting with the past brings joy, healing, and innocence.' },
      meaningReversed: { keywords: ['stuck in the past', 'naivety', 'unrealistic'], description: 'Living too much in the past prevents moving forward.' },
      description: 'The Six of Cups represents nostalgia, childhood memories, and the sweetness of the past.',
      imageUrl: '/cards/rider-waite/cups/06-cups.jpg',
    },
    {
      nameEn: 'Seven of Cups',
      nameRu: 'Семёрка Кубков',
      arcana: 'MINOR' as const,
      suit: 'CUPS' as const,
      number: 7,
      keywords: ['fantasy', 'illusion', 'wishful thinking', 'choices'],
      meaningUpright: { keywords: ['fantasy', 'illusion', 'choices'], description: 'Many options appear before you, but not all are as they seem.' },
      meaningReversed: { keywords: ['clarity', 'choices', 'sobering up'], description: 'Illusions are clearing and reality becomes visible.' },
      description: 'The Seven of Cups represents fantasy, illusion, and the challenge of making clear choices.',
      imageUrl: '/cards/rider-waite/cups/07-cups.jpg',
    },
    {
      nameEn: 'Eight of Cups',
      nameRu: 'Восьмёрка Кубков',
      arcana: 'MINOR' as const,
      suit: 'CUPS' as const,
      number: 8,
      keywords: ['disappointment', 'abandonment', 'withdrawal', 'escapism'],
      meaningUpright: { keywords: ['walking away', 'disillusionment', 'leaving'], description: 'Walking away from what no longer serves you takes courage.' },
      meaningReversed: { keywords: ['fear of moving on', 'stagnation', 'aimless drifting'], description: 'Fear is keeping you in a situation you need to leave.' },
      description: 'The Eight of Cups represents the courage to leave behind what no longer serves you.',
      imageUrl: '/cards/rider-waite/cups/08-cups.jpg',
    },
    {
      nameEn: 'Nine of Cups',
      nameRu: 'Девятка Кубков',
      arcana: 'MINOR' as const,
      suit: 'CUPS' as const,
      number: 9,
      keywords: ['contentment', 'satisfaction', 'gratitude', 'wish fulfillment'],
      meaningUpright: { keywords: ['contentment', 'satisfaction', 'wish fulfillment'], description: 'Your wishes are coming true. A time of deep satisfaction and gratitude.' },
      meaningReversed: { keywords: ['inner happiness', 'materialism', 'greed'], description: 'Seeking happiness in external things rather than within.' },
      description: 'The Nine of Cups is the wish card — contentment, satisfaction, and fulfilled desires.',
      imageUrl: '/cards/rider-waite/cups/09-cups.jpg',
    },
    {
      nameEn: 'Ten of Cups',
      nameRu: 'Десятка Кубков',
      arcana: 'MINOR' as const,
      suit: 'CUPS' as const,
      number: 10,
      keywords: ['divine love', 'blissful relationships', 'harmony', 'alignment'],
      meaningUpright: { keywords: ['happiness', 'harmony', 'family bliss'], description: 'True happiness, harmony, and emotional fulfillment in family and love.' },
      meaningReversed: { keywords: ['disconnection', 'broken family', 'misaligned values'], description: 'Family tensions or misaligned values disrupt harmony.' },
      description: 'The Ten of Cups represents the highest form of emotional fulfillment, love, and family harmony.',
      imageUrl: '/cards/rider-waite/cups/10-cups.jpg',
    },
    {
      nameEn: 'Page of Cups',
      nameRu: 'Паж Кубков',
      arcana: 'MINOR' as const,
      suit: 'CUPS' as const,
      number: 11,
      keywords: ['creative opportunities', 'intuitive messages', 'curiosity', 'possibility'],
      meaningUpright: { keywords: ['creativity', 'intuition', 'sensitivity'], description: 'A sensitive, creative soul brings intuitive messages and new possibilities.' },
      meaningReversed: { keywords: ['emotional immaturity', 'creative block', 'escaping reality'], description: 'Emotional immaturity or escapism is blocking creative flow.' },
      description: 'The Page of Cups represents creative sensitivity, intuitive messages, and emotional openness.',
      imageUrl: '/cards/rider-waite/cups/page-cups.jpg',
    },
    {
      nameEn: 'Knight of Cups',
      nameRu: 'Рыцарь Кубков',
      arcana: 'MINOR' as const,
      suit: 'CUPS' as const,
      number: 12,
      keywords: ['creativity', 'romance', 'charm', 'imagination'],
      meaningUpright: { keywords: ['romance', 'charm', 'following the heart'], description: 'Follow your heart. A romantic, imaginative energy guides the way.' },
      meaningReversed: { keywords: ['moodiness', 'disappointment', 'unrealistic'], description: 'Moodiness or unrealistic romantic ideals are causing problems.' },
      description: 'The Knight of Cups represents the romantic idealist who follows the heart above all else.',
      imageUrl: '/cards/rider-waite/cups/knight-cups.jpg',
    },
    {
      nameEn: 'Queen of Cups',
      nameRu: 'Королева Кубков',
      arcana: 'MINOR' as const,
      suit: 'CUPS' as const,
      number: 13,
      keywords: ['compassionate', 'caring', 'emotionally stable', 'intuitive'],
      meaningUpright: { keywords: ['compassion', 'intuition', 'emotional stability'], description: 'Lead with compassion and emotional intelligence. Trust your intuition.' },
      meaningReversed: { keywords: ['emotional insecurity', 'co-dependency', 'manipulation'], description: 'Emotional manipulation or insecurity disrupting relationships.' },
      description: 'The Queen of Cups embodies deep compassion, emotional wisdom, and nurturing intuition.',
      imageUrl: '/cards/rider-waite/cups/queen-cups.jpg',
    },
    {
      nameEn: 'King of Cups',
      nameRu: 'Король Кубков',
      arcana: 'MINOR' as const,
      suit: 'CUPS' as const,
      number: 14,
      keywords: ['emotionally balanced', 'compassionate', 'diplomatic', 'wise'],
      meaningUpright: { keywords: ['emotional balance', 'wisdom', 'diplomacy'], description: 'Master your emotions with wisdom and compassion. Lead with heart.' },
      meaningReversed: { keywords: ['emotional manipulation', 'moodiness', 'volatility'], description: 'Emotional volatility or manipulation undermines your authority.' },
      description: 'The King of Cups represents emotional mastery, wisdom, and the balanced integration of feeling and thought.',
      imageUrl: '/cards/rider-waite/cups/king-cups.jpg',
    },

    // ════════════════════════════════
    // MINOR ARCANA — SWORDS (14 cards)
    // ════════════════════════════════
    {
      nameEn: 'Ace of Swords',
      nameRu: 'Туз Мечей',
      arcana: 'MINOR' as const,
      suit: 'SWORDS' as const,
      number: 1,
      keywords: ['breakthrough', 'clarity', 'sharp mind', 'truth'],
      meaningUpright: { keywords: ['clarity', 'breakthrough', 'truth'], description: 'Mental clarity cuts through confusion. Truth and breakthroughs emerge.' },
      meaningReversed: { keywords: ['confusion', 'brutality', 'chaos'], description: 'Mental confusion or miscommunication is causing chaos.' },
      description: 'The Ace of Swords represents the power of the mind, clarity, and breakthrough insights.',
      imageUrl: '/cards/rider-waite/swords/ace-swords.jpg',
    },
    {
      nameEn: 'Two of Swords',
      nameRu: 'Двойка Мечей',
      arcana: 'MINOR' as const,
      suit: 'SWORDS' as const,
      number: 2,
      keywords: ['difficult decisions', 'weighing options', 'stalemate', 'blocked emotions'],
      meaningUpright: { keywords: ['stalemate', 'difficult choices', 'blocked emotions'], description: 'A difficult decision is at hand. Face the truth to find your way.' },
      meaningReversed: { keywords: ['indecision', 'confusion', 'information overload'], description: 'Confusion and indecision are prolonging a difficult situation.' },
      description: 'The Two of Swords represents the difficult choices that require seeing truth beyond our defenses.',
      imageUrl: '/cards/rider-waite/swords/02-swords.jpg',
    },
    {
      nameEn: 'Three of Swords',
      nameRu: 'Тройка Мечей',
      arcana: 'MINOR' as const,
      suit: 'SWORDS' as const,
      number: 3,
      keywords: ['heartbreak', 'emotional pain', 'sorrow', 'grief'],
      meaningUpright: { keywords: ['heartbreak', 'suffering', 'grief'], description: 'Pain and heartbreak are present. Allow yourself to grieve and heal.' },
      meaningReversed: { keywords: ['negative self-talk', 'releasing pain', 'optimism'], description: 'Beginning to release pain and find optimism again.' },
      description: 'The Three of Swords represents heartbreak, grief, and the pain of emotional wounds.',
      imageUrl: '/cards/rider-waite/swords/03-swords.jpg',
    },
    {
      nameEn: 'Four of Swords',
      nameRu: 'Четвёрка Мечей',
      arcana: 'MINOR' as const,
      suit: 'SWORDS' as const,
      number: 4,
      keywords: ['rest', 'restoration', 'contemplation', 'recuperation'],
      meaningUpright: { keywords: ['rest', 'recuperation', 'quiet'], description: 'Rest and recuperation are needed. Step back and restore your energy.' },
      meaningReversed: { keywords: ['restlessness', 'burnout', 'stagnation'], description: 'Inability to rest or restlessness preventing recovery.' },
      description: 'The Four of Swords represents the necessity of rest, recuperation, and quiet contemplation.',
      imageUrl: '/cards/rider-waite/swords/04-swords.jpg',
    },
    {
      nameEn: 'Five of Swords',
      nameRu: 'Пятёрка Мечей',
      arcana: 'MINOR' as const,
      suit: 'SWORDS' as const,
      number: 5,
      keywords: ['conflict', 'disagreements', 'competition', 'defeat'],
      meaningUpright: { keywords: ['conflict', 'defeat', 'win at all costs'], description: 'A hollow victory or a conflict where everyone loses something.' },
      meaningReversed: { keywords: ['reconciliation', 'making amends', 'past resentment'], description: 'Working through conflict toward reconciliation and healing.' },
      description: 'The Five of Swords represents conflict, defeat, and the cost of winning at any price.',
      imageUrl: '/cards/rider-waite/swords/05-swords.jpg',
    },
    {
      nameEn: 'Six of Swords',
      nameRu: 'Шестёрка Мечей',
      arcana: 'MINOR' as const,
      suit: 'SWORDS' as const,
      number: 6,
      keywords: ['transition', 'change', 'rite of passage', 'releasing baggage'],
      meaningUpright: { keywords: ['transition', 'moving on', 'calmer waters'], description: 'Moving toward calmer waters after a period of difficulty.' },
      meaningReversed: { keywords: ['stuck in the past', 'unresolved issues', 'resistance'], description: 'Resistance to necessary change keeps you in troubled waters.' },
      description: 'The Six of Swords represents transition, moving forward, and the journey toward calmer shores.',
      imageUrl: '/cards/rider-waite/swords/06-swords.jpg',
    },
    {
      nameEn: 'Seven of Swords',
      nameRu: 'Семёрка Мечей',
      arcana: 'MINOR' as const,
      suit: 'SWORDS' as const,
      number: 7,
      keywords: ['betrayal', 'deception', 'getting away with something', 'strategy'],
      meaningUpright: { keywords: ['deception', 'betrayal', 'strategy'], description: 'Deception or betrayal may be at play. Use strategy wisely.' },
      meaningReversed: { keywords: ['conscience', 'coming clean', 'exposure'], description: 'Deception is being revealed. An opportunity to come clean.' },
      description: 'The Seven of Swords represents strategy, deception, and the ethics of cunning behavior.',
      imageUrl: '/cards/rider-waite/swords/07-swords.jpg',
    },
    {
      nameEn: 'Eight of Swords',
      nameRu: 'Восьмёрка Мечей',
      arcana: 'MINOR' as const,
      suit: 'SWORDS' as const,
      number: 8,
      keywords: ['negative thoughts', 'self-imposed restriction', 'imprisonment', 'victim mentality'],
      meaningUpright: { keywords: ['restriction', 'trapped', 'victim mentality'], description: 'You feel trapped, but the bonds are largely self-imposed. Free your mind.' },
      meaningReversed: { keywords: ['self-acceptance', 'new perspective', 'freedom'], description: 'Breaking free from self-imposed limitations and negative thinking.' },
      description: 'The Eight of Swords represents feeling trapped by self-imposed mental restrictions and limiting beliefs.',
      imageUrl: '/cards/rider-waite/swords/08-swords.jpg',
    },
    {
      nameEn: 'Nine of Swords',
      nameRu: 'Девятка Мечей',
      arcana: 'MINOR' as const,
      suit: 'SWORDS' as const,
      number: 9,
      keywords: ['anxiety', 'worry', 'fear', 'depression'],
      meaningUpright: { keywords: ['anxiety', 'worry', 'nightmares'], description: 'Anxiety and worry are overwhelming your mind. Seek help and perspective.' },
      meaningReversed: { keywords: ['inner turmoil', 'fear', 'recovering from trauma'], description: 'Beginning to recover from anxiety and face inner fears.' },
      description: 'The Nine of Swords represents anxiety, nightmares, and the suffering caused by our own thoughts.',
      imageUrl: '/cards/rider-waite/swords/09-swords.jpg',
    },
    {
      nameEn: 'Ten of Swords',
      nameRu: 'Десятка Мечей',
      arcana: 'MINOR' as const,
      suit: 'SWORDS' as const,
      number: 10,
      keywords: ['painful endings', 'deep wounds', 'betrayal', 'loss'],
      meaningUpright: { keywords: ['painful endings', 'betrayal', 'crisis'], description: 'A painful ending. Though it hurts, this is the lowest point and dawn is near.' },
      meaningReversed: { keywords: ['recovery', 'regeneration', 'survival'], description: 'Rising from the ashes after a painful ending. Recovery begins.' },
      description: 'The Ten of Swords represents painful endings, betrayal, and the darkest moment before dawn.',
      imageUrl: '/cards/rider-waite/swords/10-swords.jpg',
    },
    {
      nameEn: 'Page of Swords',
      nameRu: 'Паж Мечей',
      arcana: 'MINOR' as const,
      suit: 'SWORDS' as const,
      number: 11,
      keywords: ['new ideas', 'curiosity', 'thirst for knowledge', 'new ways of communicating'],
      meaningUpright: { keywords: ['curiosity', 'mental alertness', 'new ideas'], description: 'A curious, alert mind seeks new information and speaks truth.' },
      meaningReversed: { keywords: ['deception', 'manipulation', 'gossip'], description: 'Gossip, manipulation, or using words as weapons.' },
      description: 'The Page of Swords represents intellectual curiosity, mental alertness, and the thirst for truth.',
      imageUrl: '/cards/rider-waite/swords/page-swords.jpg',
    },
    {
      nameEn: 'Knight of Swords',
      nameRu: 'Рыцарь Мечей',
      arcana: 'MINOR' as const,
      suit: 'SWORDS' as const,
      number: 12,
      keywords: ['ambitious', 'action-oriented', 'driven to succeed', 'fast-thinking'],
      meaningUpright: { keywords: ['action', 'ambition', 'quick thinking'], description: 'Act decisively and with intellectual clarity. Speed is of the essence.' },
      meaningReversed: { keywords: ['scattered energy', 'recklessness', 'tyrant'], description: 'Reckless actions or scattered mental energy causing harm.' },
      description: 'The Knight of Swords represents swift, decisive action driven by intellect and ambition.',
      imageUrl: '/cards/rider-waite/swords/knight-swords.jpg',
    },
    {
      nameEn: 'Queen of Swords',
      nameRu: 'Королева Мечей',
      arcana: 'MINOR' as const,
      suit: 'SWORDS' as const,
      number: 13,
      keywords: ['independent', 'unbiased judgement', 'clear boundaries', 'direct communication'],
      meaningUpright: { keywords: ['clarity', 'independence', 'direct communication'], description: 'Communicate clearly and directly. Set firm boundaries with compassion.' },
      meaningReversed: { keywords: ['coldness', 'cruelty', 'bitterness'], description: 'Coldness, cruelty, or using truth as a weapon without compassion.' },
      description: 'The Queen of Swords represents clear-headed independence, sharp wit, and honest communication.',
      imageUrl: '/cards/rider-waite/swords/queen-swords.jpg',
    },
    {
      nameEn: 'King of Swords',
      nameRu: 'Король Мечей',
      arcana: 'MINOR' as const,
      suit: 'SWORDS' as const,
      number: 14,
      keywords: ['mental clarity', 'intellectual power', 'authority', 'truth'],
      meaningUpright: { keywords: ['authority', 'clarity', 'truth', 'intellectual power'], description: 'Lead with intellectual clarity and moral authority. Speak truth.' },
      meaningReversed: { keywords: ['manipulative', 'tyrannical', 'abuse of power'], description: 'Intellectual arrogance or abuse of authority through manipulation.' },
      description: 'The King of Swords represents intellectual mastery, moral authority, and the power of clear thought.',
      imageUrl: '/cards/rider-waite/swords/king-swords.jpg',
    },

    // ══════════════════════════════════
    // MINOR ARCANA — PENTACLES (14 cards)
    // ══════════════════════════════════
    {
      nameEn: 'Ace of Pentacles',
      nameRu: 'Туз Пентаклей',
      arcana: 'MINOR' as const,
      suit: 'PENTACLES' as const,
      number: 1,
      keywords: ['new financial opportunity', 'manifestation', 'abundance', 'security'],
      meaningUpright: { keywords: ['opportunity', 'prosperity', 'manifestation'], description: 'A new material or financial opportunity emerges. Seize it with both hands.' },
      meaningReversed: { keywords: ['missed opportunity', 'lack of planning', 'scarcity'], description: 'A financial opportunity is being missed or resources are mismanaged.' },
      description: 'The Ace of Pentacles represents new material beginnings, prosperity, and the seed of abundance.',
      imageUrl: '/cards/rider-waite/pentacles/ace-pentacles.jpg',
    },
    {
      nameEn: 'Two of Pentacles',
      nameRu: 'Двойка Пентаклей',
      arcana: 'MINOR' as const,
      suit: 'PENTACLES' as const,
      number: 2,
      keywords: ['multiple priorities', 'time management', 'prioritization', 'adaptability'],
      meaningUpright: { keywords: ['balance', 'adaptability', 'time management'], description: 'Juggling multiple priorities requires balance and adaptability.' },
      meaningReversed: { keywords: ['disorganization', 'imbalance', 'overwhelmed'], description: 'Overwhelmed by too many obligations. Prioritize ruthlessly.' },
      description: 'The Two of Pentacles represents the balancing act of managing multiple priorities and resources.',
      imageUrl: '/cards/rider-waite/pentacles/02-pentacles.jpg',
    },
    {
      nameEn: 'Three of Pentacles',
      nameRu: 'Тройка Пентаклей',
      arcana: 'MINOR' as const,
      suit: 'PENTACLES' as const,
      number: 3,
      keywords: ['teamwork', 'collaboration', 'learning', 'implementation'],
      meaningUpright: { keywords: ['teamwork', 'collaboration', 'skill'], description: 'Working together brings mastery. Collaboration produces excellence.' },
      meaningReversed: { keywords: ['lack of teamwork', 'disorganization', 'group conflict'], description: 'Poor collaboration or lack of alignment is undermining the work.' },
      description: 'The Three of Pentacles represents skilled teamwork, craftsmanship, and collaborative achievement.',
      imageUrl: '/cards/rider-waite/pentacles/03-pentacles.jpg',
    },
    {
      nameEn: 'Four of Pentacles',
      nameRu: 'Четвёрка Пентаклей',
      arcana: 'MINOR' as const,
      suit: 'PENTACLES' as const,
      number: 4,
      keywords: ['saving money', 'security', 'conservatism', 'scarcity'],
      meaningUpright: { keywords: ['security', 'conservation', 'control'], description: 'Holding tightly to resources and security. Find the balance between saving and living.' },
      meaningReversed: { keywords: ['greed', 'materialism', 'self-protection'], description: 'Excessive attachment to material things is limiting true abundance.' },
      description: 'The Four of Pentacles represents the need for security and the shadow of possessiveness.',
      imageUrl: '/cards/rider-waite/pentacles/04-pentacles.jpg',
    },
    {
      nameEn: 'Five of Pentacles',
      nameRu: 'Пятёрка Пентаклей',
      arcana: 'MINOR' as const,
      suit: 'PENTACLES' as const,
      number: 5,
      keywords: ['financial loss', 'poverty', 'lack mindset', 'isolation'],
      meaningUpright: { keywords: ['financial loss', 'poverty', 'hardship'], description: 'A time of material hardship. Seek support — help is available.' },
      meaningReversed: { keywords: ['recovery', 'financial improvement', 'new mindset'], description: 'Beginning to recover from financial or spiritual poverty.' },
      description: 'The Five of Pentacles represents hardship, financial struggle, and the need to seek help.',
      imageUrl: '/cards/rider-waite/pentacles/05-pentacles.jpg',
    },
    {
      nameEn: 'Six of Pentacles',
      nameRu: 'Шестёрка Пентаклей',
      arcana: 'MINOR' as const,
      suit: 'PENTACLES' as const,
      number: 6,
      keywords: ['giving', 'receiving', 'sharing wealth', 'generosity'],
      meaningUpright: { keywords: ['generosity', 'charity', 'giving and receiving'], description: 'The flow of generosity creates abundance. Give and receive freely.' },
      meaningReversed: { keywords: ['debt', 'selfishness', 'power and domination'], description: 'Imbalance in giving and receiving, or strings attached to generosity.' },
      description: 'The Six of Pentacles represents generosity, the flow of resources, and balanced exchange.',
      imageUrl: '/cards/rider-waite/pentacles/06-pentacles.jpg',
    },
    {
      nameEn: 'Seven of Pentacles',
      nameRu: 'Семёрка Пентаклей',
      arcana: 'MINOR' as const,
      suit: 'PENTACLES' as const,
      number: 7,
      keywords: ['long-term view', 'sustainable results', 'perseverance', 'investment'],
      meaningUpright: { keywords: ['patience', 'investment', 'long-term vision'], description: 'Patient investment is growing. Trust the long-term process.' },
      meaningReversed: { keywords: ['lack of long-term vision', 'limited success', 'impatience'], description: 'Impatience or lack of vision is undermining long-term success.' },
      description: 'The Seven of Pentacles represents patient investment, long-term thinking, and sustainable growth.',
      imageUrl: '/cards/rider-waite/pentacles/07-pentacles.jpg',
    },
    {
      nameEn: 'Eight of Pentacles',
      nameRu: 'Восьмёрка Пентаклей',
      arcana: 'MINOR' as const,
      suit: 'PENTACLES' as const,
      number: 8,
      keywords: ['apprenticeship', 'repetitive tasks', 'mastery', 'skill development'],
      meaningUpright: { keywords: ['diligence', 'mastery', 'skill development'], description: 'Dedicated practice and diligent work leads to mastery.' },
      meaningReversed: { keywords: ['perfectionism', 'misdirected activity', 'no ambition'], description: 'Perfectionism or lack of focus is impeding skill development.' },
      description: 'The Eight of Pentacles represents diligent practice, skill development, and the path to mastery.',
      imageUrl: '/cards/rider-waite/pentacles/08-pentacles.jpg',
    },
    {
      nameEn: 'Nine of Pentacles',
      nameRu: 'Девятка Пентаклей',
      arcana: 'MINOR' as const,
      suit: 'PENTACLES' as const,
      number: 9,
      keywords: ['abundance', 'luxury', 'self-sufficiency', 'financial independence'],
      meaningUpright: { keywords: ['abundance', 'independence', 'self-sufficiency'], description: 'You have achieved a beautiful level of independence and abundance.' },
      meaningReversed: { keywords: ['self-worth', 'over-investment in work', 'hustling'], description: 'Overworking or neglecting life beyond material success.' },
      description: 'The Nine of Pentacles represents self-sufficiency, luxury, and the fruits of hard-won independence.',
      imageUrl: '/cards/rider-waite/pentacles/09-pentacles.jpg',
    },
    {
      nameEn: 'Ten of Pentacles',
      nameRu: 'Десятка Пентаклей',
      arcana: 'MINOR' as const,
      suit: 'PENTACLES' as const,
      number: 10,
      keywords: ['wealth', 'financial security', 'family', 'long-term success'],
      meaningUpright: { keywords: ['legacy', 'family wealth', 'long-term success'], description: 'A legacy of wealth and stability is built for future generations.' },
      meaningReversed: { keywords: ['the dark side of wealth', 'financial failure', 'conflict'], description: 'Financial instability or family conflict threatens lasting security.' },
      description: 'The Ten of Pentacles represents lasting wealth, family legacy, and multigenerational abundance.',
      imageUrl: '/cards/rider-waite/pentacles/10-pentacles.jpg',
    },
    {
      nameEn: 'Page of Pentacles',
      nameRu: 'Паж Пентаклей',
      arcana: 'MINOR' as const,
      suit: 'PENTACLES' as const,
      number: 11,
      keywords: ['manifestation', 'financial opportunity', 'skill development', 'ambition'],
      meaningUpright: { keywords: ['ambition', 'desire', 'diligence'], description: 'A new opportunity for learning and material growth is available.' },
      meaningReversed: { keywords: ['lack of progress', 'procrastination', 'immaturity'], description: 'Procrastination or lack of focus is blocking material progress.' },
      description: 'The Page of Pentacles represents ambition, new opportunities, and the desire to learn and grow.',
      imageUrl: '/cards/rider-waite/pentacles/page-pentacles.jpg',
    },
    {
      nameEn: 'Knight of Pentacles',
      nameRu: 'Рыцарь Пентаклей',
      arcana: 'MINOR' as const,
      suit: 'PENTACLES' as const,
      number: 12,
      keywords: ['hard work', 'productivity', 'routine', 'conventionalism'],
      meaningUpright: { keywords: ['hard work', 'efficiency', 'routine'], description: 'Steady, methodical effort produces reliable results. Trust the process.' },
      meaningReversed: { keywords: ['laziness', 'boredom', 'feeling stuck'], description: 'Boredom or excessive caution is slowing necessary progress.' },
      description: 'The Knight of Pentacles represents steady, reliable effort and methodical progress toward goals.',
      imageUrl: '/cards/rider-waite/pentacles/knight-pentacles.jpg',
    },
    {
      nameEn: 'Queen of Pentacles',
      nameRu: 'Королева Пентаклей',
      arcana: 'MINOR' as const,
      suit: 'PENTACLES' as const,
      number: 13,
      keywords: ['nurturing', 'practical', 'providing financially', 'a working parent'],
      meaningUpright: { keywords: ['practicality', 'nurturing', 'financial security'], description: 'Nurture your practical affairs with warmth and financial wisdom.' },
      meaningReversed: { keywords: ['financial independence', 'self-care', 'work-home conflict'], description: 'Imbalance between material and nurturing responsibilities.' },
      description: 'The Queen of Pentacles embodies practical nurturing, financial wisdom, and grounded abundance.',
      imageUrl: '/cards/rider-waite/pentacles/queen-pentacles.jpg',
    },
    {
      nameEn: 'King of Pentacles',
      nameRu: 'Король Пентаклей',
      arcana: 'MINOR' as const,
      suit: 'PENTACLES' as const,
      number: 14,
      keywords: ['wealth', 'business', 'leadership', 'security', 'discipline'],
      meaningUpright: { keywords: ['wealth', 'security', 'discipline', 'abundance'], description: 'Master of the material world. Lead with generosity and proven wisdom.' },
      meaningReversed: { keywords: ['financially inept', 'obsessed with wealth', 'stubbornness'], description: 'Obsession with material success or misuse of financial power.' },
      description: 'The King of Pentacles represents mastery of the material world, financial authority, and generous abundance.',
      imageUrl: '/cards/rider-waite/pentacles/king-pentacles.jpg',
    },
  ]

  console.log(`📦 Seeding ${cards.length} cards...`)

  for (const card of cards) {
    await prisma.card.create({
      data: {
        ...card,
        deckId: deck.id,
      },
    })
  }

  console.log(`✅ ${cards.length} cards seeded successfully!`)
  console.log('🔮 Mystic Tarot database is ready!')
}

main()
  .catch((e) => {
    console.error('❌ Seed failed:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })